# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.disksize.size = '50GB'


  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.box = "ubuntu/xenial64"
    master.vm.network "private_network", ip: "172.16.33.31"
    master.vm.provision "shell", inline: "sed 's/127\.0\.1\.1.*master.*/172\.16\.33\.31 master/' -i /etc/hosts"
    for p in [:virtualbox, :libvirt] do
      master.vm.provider p do |provider|
        provider.memory = 2048
        provider.cpus = 2
      end
    end
  end

  config.vm.define "ketcd" do |ketcd|
    ketcd.vm.hostname = "ketcd"
    ketcd.vm.box = "ubuntu/xenial64"
    ketcd.vm.network "private_network", ip: "172.16.33.32"
    ketcd.vm.provision "shell", inline: "sed 's/127\.0\.1\.1.*ketcd.*/172\.16\.33\.32 ketcd/' -i /etc/hosts"
    for p in [:virtualbox, :libvirt] do
      ketcd.vm.provider p do |provider|
        provider.memory = 2048
        provider.cpus = 4
      end
    end
  end

  config.vm.define "node" do |node|
    node.vm.hostname = "node"
    node.vm.box = "ubuntu/xenial64"
    node.vm.network "private_network", ip: "172.16.33.33"
    node.vm.provision "shell", inline: "sed 's/127\.0\.1\.1.*node.*/172\.16\.33\.33 node/' -i /etc/hosts"
    for p in [:virtualbox, :libvirt] do
      node.vm.provider p do |provider|
        provider.memory = 2048
        provider.cpus = 3
      end
    end
  end

end
