# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.disksize.size = '50GB'


  config.vm.define "master1" do |master1|
    master1.vm.hostname = "master1"
    master1.vm.box = "ubuntu/xenial64"
    master1.vm.network "private_network", ip: "172.16.33.20"
    master1.vm.provision "shell", inline: "sed 's/127\.0\.1\.1.*master1.*/172\.16\.33\.20 master1/' -i /etc/hosts"
    for p in [:virtualbox, :libvirt] do
      master1.vm.provider p do |provider|
        provider.memory = 2048
        provider.cpus = 2
      end
    end
  end

  config.vm.define "master2" do |master2|
    master2.vm.hostname = "master2"
    master2.vm.box = "ubuntu/xenial64"
    master2.vm.network "private_network", ip: "172.16.33.21"
    master2.vm.provision "shell", inline: "sed 's/127\.0\.1\.1.*master2.*/172\.16\.33\.21 master2/' -i /etc/hosts"
    for p in [:virtualbox, :libvirt] do
      master2.vm.provider p do |provider|
        provider.memory = 2048
        provider.cpus = 4
      end
    end
  end

  config.vm.define "master3" do |master3|
    master3.vm.hostname = "master3"
    master3.vm.box = "ubuntu/xenial64"
    master3.vm.network "private_network", ip: "172.16.33.22"
    master3.vm.provision "shell", inline: "sed 's/127\.0\.1\.1.*master3.*/172\.16\.33\.22 master3/' -i /etc/hosts"
    for p in [:virtualbox, :libvirt] do
      master3.vm.provider p do |provider|
        provider.memory = 2048
        provider.cpus = 3
      end
    end
  end

  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.box = "ubuntu/xenial64"
    node1.vm.network "private_network", ip: "172.16.33.23"
    node1.vm.provision "shell", inline: "sed 's/127\.0\.1\.1.*node1.*/172\.16\.33\.23 node1/' -i /etc/hosts"
    for p in [:virtualbox, :libvirt] do
      node1.vm.provider p do |provider|
        provider.memory = 2048
        provider.cpus = 3
      end
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.box = "ubuntu/xenial64"
    node2.vm.network "private_network", ip: "172.16.33.24"
    node2.vm.provision "shell", inline: "sed 's/127\.0\.1\.1.*node2.*/172\.16\.33\.24 node2/' -i /etc/hosts"
    for p in [:virtualbox, :libvirt] do
      node2.vm.provider p do |provider|
        provider.memory = 2048
        provider.cpus = 3
      end
    end
  end

  config.vm.define "node3" do |node3|
    node3.vm.hostname = "node3"
    node3.vm.box = "ubuntu/xenial64"
    node3.vm.network "private_network", ip: "172.16.33.25"
    node3.vm.provision "shell", inline: "sed 's/127\.0\.1\.1.*node3.*/172\.16\.33\.25 node3/' -i /etc/hosts"
    for p in [:virtualbox, :libvirt] do
      node3.vm.provider p do |provider|
        provider.memory = 2048
        provider.cpus = 3
      end
    end
  end


end
